apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: nginx
        image: {{.Values.image.name}}
        ports:
        - containerPort: {{.Values.image.port}}
